# Generated by Django 5.1.1 on 2024-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Username")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
                (
                    "pwssword_re_type",
                    models.CharField(max_length=50, verbose_name="Repeat Password"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last Name"),
                ),
                ("uniqueID", models.BigIntegerField(verbose_name="Unique ID")),
                ("date_of_birth", models.DateField(verbose_name="Date Of Borth")),
            ],
        ),
    ]
