# Generated by Django 5.1.1 on 2024-09-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commeninfo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="pwssword_re_type",
            new_name="password_re_type",
        ),
    ]
