# Generated by Django 5.1.1 on 2024-09-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commeninfo", "0002_rename_pwssword_re_type_userinfo_password_re_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="uniqueID",
        ),
    ]
