# Generated by Django 5.1.1 on 2024-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commeninfo", "0003_remove_userinfo_uniqueid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="uniqueID",
            field=models.IntegerField(default=1, unique=True, verbose_name="Unique ID"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="date_of_birth",
            field=models.DateField(blank=True, verbose_name="Date Of Borth"),
        ),
    ]
